//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AES.EncryptDecrypt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AES.EncryptDecrypt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0e	0b	0d	09
        ///09	0e	0b	0d
        ///0d	09	0e	0b
        ///0b	0d	09	0e.
        /// </summary>
        public static string inverse_mix_column_constant {
            get {
                return ResourceManager.GetString("inverse_mix_column_constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52	09	6a	d5	30	36	a5	38	bf	40	a3	9e	81	f3	d7	fb
        ///7c	e3	39	82	9b	2f	ff	87	34	8e	43	44	c4	de	e9	cb
        ///54	7b	94	32	a6	c2	23	3d	ee	4c	95	0b	42	fa	c3	4e
        ///08	2e	a1	66	28	d9	24	b2	76	5b	a2	49	6d	8b	d1	25
        ///72	f8	f6	64	86	68	98	16	d4	a4	5c	cc	5d	65	b6	92
        ///6c	70	48	50	fd	ed	b9	da	5e	15	46	57	a7	8d	9d	84
        ///90	d8	ab	00	8c	bc	d3	0a	f7	e4	58	05	b8	b3	45	06
        ///d0	2c	1e	8f	ca	3f	0f	02	c1	af	bd	03	01	13	8a	6b
        ///3a	91	11	41	4f	67	dc	ea	97	f2	cf	ce	f0	b4	e6	73
        ///96	ac	74	22	e7	ad	35	85	e2	f9	37	e8	1c	75	df	6e
        ///47	f1	1a	71	1d	29	c5	8 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string inverse_s_box {
            get {
                return ResourceManager.GetString("inverse_s_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01	00	00	00
        ///02	00	00	00
        ///04	00	00	00
        ///08	00	00	00
        ///10	00	00	00
        ///20	00	00	00
        ///40	00	00	00
        ///80	00	00	00
        ///1b	00	00	00
        ///36	00	00	00.
        /// </summary>
        public static string key_constant {
            get {
                return ResourceManager.GetString("key_constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02	03	01	01
        ///01	02	03	01
        ///01	01	02	03
        ///03	01	01	02.
        /// </summary>
        public static string mix_column_constant {
            get {
                return ResourceManager.GetString("mix_column_constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 63	7c	77	7b	f2	6b	6f	c5	30	01	67	2b	fe	d7	ab	76
        ///ca	82	c9	7d	fa	59	47	f0	ad	d4	a2	af	9c	a4	72	c0
        ///b7	fd	93	26	36	3f	f7	cc	34	a5	e5	f1	71	d8	31	15
        ///04	c7	23	c3	18	96	05	9a	07	12	80	e2	eb	27	b2	75
        ///09	83	2c	1a	1b	6e	5a	a0	52	3b	d6	b3	29	e3	2f	84
        ///53	d1	00	ed	20	fc	b1	5b	6a	cb	be	39	4a	4c	58	cf
        ///d0	ef	aa	fb	43	4d	33	85	45	f9	02	7f	50	3c	9f	a8
        ///51	a3	40	8f	92	9d	38	f5	bc	b6	da	21	10	ff	f3	d2
        ///cd	0c	13	ec	5f	97	44	17	c4	a7	7e	3d	64	5d	19	73
        ///60	81	4f	dc	22	2a	90	88	46	ee	b8	14	de	5e	0b	db
        ///e0	32	3a	0a	49	06	24	5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string s_box {
            get {
                return ResourceManager.GetString("s_box", resourceCulture);
            }
        }
    }
}
